export default [
  {
    id: '1',
    image: 'images/expresso-tradicional.svg',
    type: ['tradicional'],
    name: 'Expresso Tradicional',
    description: 'O tradicional café feito com água quente e grãos moídos',
    price: 7.59,
  },
  {
    id: '2',
    image: 'images/expresso-americano.svg',
    type: ['tradicional'],
    name: 'Expresso Americano',
    description: 'Expresso diluído, menos intenso que o tradicional',
    price: 7.59,
  },
  {
    id: '3',
    image: 'images/expresso-cremoso.svg',
    type: ['tradicional'],
    name: 'Expresso Cremoso',
    description: 'Café expresso tradicional com espuma cremosa',
    price: 8.8,
  },
  {
    id: '4',
    image: 'images/expresso-gelado.svg',
    type: ['tradicional', 'gelado'],
    name: 'Expresso Gelado',
    description: 'Bebida preparada com café expresso e cubos de gelo',
    price: 9.9,
  },
  {
    id: '5',
    image: 'images/cafe-com-leite.svg',
    type: ['tradicional', 'com leite'],
    name: 'Café com Leite',
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    price: 12.29,
  },
  {
    id: '6',
    image: 'images/latte.svg',
    type: ['tradicional', 'com leite'],
    name: 'Latte',
    description:
      'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    price: 12.29,
  },
  {
    id: '7',
    image: 'images/capuccino.svg',
    type: ['tradicional', 'com leite'],
    name: 'Capuccino',
    description:
      'Bebida com canela feita de doses iguais de café, leite e espuma',
    price: 12.29,
  },
  {
    id: '8',
    image: 'images/macchiato.svg',
    type: ['tradicional', 'com leite'],
    name: 'Macchiato',
    description:
      'Café expresso misturado com um pouco de leite quente e espuma',
    price: 12.29,
  },
  {
    id: '9',
    image: 'images/mocaccino.svg',
    type: ['tradicional', 'com leite'],
    name: 'Mocaccino',
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    price: 12.29,
  },
  {
    id: '10',
    image: 'images/chocolate-quente.svg',
    type: ['especial', 'com leite'],
    name: 'Chocolate Quente',
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    price: 12.29,
  },
  {
    id: '11',
    image: 'images/cubano.svg',
    type: ['especial', 'alcoólico', 'gelado'],
    name: 'Cubano',
    description:
      'Drink gelado de café expresso com rum, creme de leite e hortelã',
    price: 16.39,
  },
  {
    id: '12',
    image: 'images/havaiano.svg',
    type: ['especial'],
    name: 'Havaiano',
    description: 'Bebida adocicada preparada com café e leite de cocoa',
    price: 24.9,
  },
  {
    id: '13',
    image: 'images/arabe.svg',
    type: ['especial'],
    name: 'Árabe',
    description: 'Bebida preparada com grãos de café árabe e especiarias',
    price: 24.9,
  },
  {
    id: '14',
    image: 'images/irlandes.svg',
    type: ['especial', 'alcoólico'],
    name: 'Irlandês',
    description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    price: 24.9,
  },
]
